# Generated by Django 4.1.2 on 2022-11-03 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='Vehicle identification number (VIN)')),
                ('assembly_date', models.DateField()),
                ('entry_into_service', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RearAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='ADA1100', max_length=12)),
                ('oil_filter', models.CharField(default='Има', max_length=12)),
                ('gear_first', models.CharField(default='R780', max_length=12)),
                ('serial_no', models.CharField(default='2418002', max_length=12)),
                ('gear_ratio', models.CharField(default='3.08', max_length=12)),
                ('diferential_block', models.CharField(default='Има', max_length=12)),
                ('hub_reduction', models.CharField(default='Нема', max_length=12)),
                ('tag_axle_preparation', models.CharField(default='Нема', max_length=12)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='LicencePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('is_valid', models.BooleanField()),
                ('validity', models.DateField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FrontAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='AM740', max_length=12)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='EngineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke_volume', models.CharField(default='13', max_length=2)),
                ('power_code', models.CharField(default='410hp', max_length=5)),
                ('type_vehicle', models.CharField(default='DC13 115/410hp', max_length=14)),
                ('type_symbol', models.CharField(default='DC13 115 L01', max_length=12)),
                ('serial_no', models.CharField(max_length=7)),
                ('cylinder_block_generation', models.CharField(default='2', max_length=1)),
                ('speed_limit_with_low_oil_presure', models.CharField(default='Without', max_length=14)),
                ('egr_system', models.CharField(default='Without', max_length=14)),
                ('egr_cooling', models.CharField(default='Not valid', max_length=14)),
                ('emmission_level', models.CharField(default='Euro 6', max_length=14)),
                ('management_system', models.CharField(default='S8', max_length=2)),
                ('nox_control', models.CharField(default='With', max_length=14)),
                ('torque_reduction_nox_control', models.CharField(default='With', max_length=14)),
                ('power_take_of_ED', models.CharField(default='Prepared', max_length=24)),
                ('power_take_of_ED_electical_preparation', models.CharField(default='Without', max_length=24)),
                ('power_take_of_ED_control', models.CharField(default='Without', max_length=14)),
                ('turbocharger_duty_class', models.CharField(default='Специјална', max_length=14)),
                ('precleaner_air_intake', models.CharField(default='Without', max_length=14)),
                ('air_intake', models.CharField(default='Front, normal', max_length=18)),
                ('air_cleaner_engine_fire_resistant', models.CharField(default='Without', max_length=14)),
                ('air_cleaner_safety_filter', models.CharField(default='Without', max_length=14)),
                ('air_cleaner_engine_paper_area', models.CharField(default='13m²', max_length=14)),
                ('air_intake_throttle_engine', models.CharField(default='With', max_length=14)),
                ('air_intake_throttle_control', models.CharField(default='Electronic', max_length=14)),
                ('air_filter_clogged_indicator', models.CharField(default='Electronic', max_length=14)),
                ('noise_dampering', models.CharField(default='80 dBA acc to 70/157/EEC', max_length=64)),
                ('noise_encapsulation_engine', models.CharField(default='With absorbents', max_length=18)),
                ('crankcase_ventilation_type', models.CharField(default='Open', max_length=14)),
                ('crankcase_ventilation_antitreeze', models.CharField(default='Without', max_length=14)),
                ('oil_level_sensor_engine', models.CharField(default='Without', max_length=14)),
                ('oil_level_sensor_monitoring', models.CharField(default='Without', max_length=14)),
                ('oil_sump_material', models.CharField(default='Пластика', max_length=14)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='EngineControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_limiter', models.CharField(default='Има', max_length=12)),
                ('speed_limitаtion', models.CharField(default='85km/h', max_length=12)),
                ('speed_limit_second', models.CharField(default='Нема', max_length=12)),
                ('speed_limit_third', models.CharField(default='Нема', max_length=12)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ComplementaryEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fifth_wheel', models.CharField(default='JOST JSK37C-Z 150', max_length=24)),
                ('fifth_wheel_position', models.CharField(default='660', max_length=12)),
                ('fifth_wheel_category', models.CharField(default='Fixed, plate-mounted', max_length=24)),
                ('fifth_wheel_mounting_plate', models.CharField(default='40mm Dmax:152kN', max_length=24)),
                ('catwalk', models.CharField(default='Единечна', max_length=24)),
                ('bracket_front_mounted_equipment', models.CharField(default='Нема', max_length=24)),
                ('acl_aut_chassis_lubrication', models.CharField(default='Нема', max_length=24, verbose_name='ACL, automatic chassis lubrication')),
                ('dimension_ja_bep_lo2o', models.CharField(default='775', max_length=24, verbose_name='Dimesion JA/BEP L020')),
                ('trailer_electric_connector', models.CharField(default='1x15 pole', max_length=24)),
                ('trailer_connector_type', models.CharField(default='High', max_length=24)),
                ('side_skirts', models.CharField(default='Without', max_length=36)),
                ('resque_equip_except_fire_ex', models.CharField(default='With', max_length=24)),
                ('hose_tyre_inflation', models.CharField(default='20', max_length=24)),
                ('spare_wheel_carrier', models.CharField(default='Without', max_length=24)),
                ('fire_extinguisher', models.CharField(default='1 x 2kg', max_length=24)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.vehicle')),
            ],
        ),
    ]
