# Generated by Django 4.1.3 on 2022-11-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
