# Generated by Django 4.1.3 on 2022-11-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementaryequipment',
            name='fifth_wheel_category',
            field=models.CharField(default='Fixed, plate-mounted', max_length=32),
        ),
    ]
