# Generated by Django 4.1.3 on 2022-11-06 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_complementaryequipment_fifth_wheel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_level', models.CharField(default='Комплетно изграден', max_length=24)),
                ('production_class', models.CharField(default='Камион', max_length=24)),
                ('development_level', models.CharField(default='5', max_length=2)),
                ('front_wheel_drive', models.CharField(default='Нема', max_length=6)),
                ('axle_distance', models.CharField(default='3700mm', max_length=14)),
                ('chassis_width', models.CharField(default='2550mm', max_length=18)),
                ('chassis_adaptation', models.CharField(default='A, има водечка спојка која овозможува оштро свртување', max_length=64)),
                ('transport_type', models.CharField(default='L', max_length=2)),
                ('duty_class', models.CharField(default='M', max_length=2)),
                ('chassis_height', models.CharField(default='N, Нормална', max_length=12)),
                ('plate_language', models.CharField(default='English', max_length=12)),
                ('axle_weight_front_technical', models.CharField(default='7500kg', max_length=12)),
                ('axle_load_rear_technical', models.CharField(default='115000kg', max_length=12)),
                ('total_weight', models.CharField(default='19000kg', max_length=12)),
                ('preparation_for_toll_collect', models.CharField(default='Има', max_length=6)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.vehicle')),
            ],
        ),
    ]
