# Generated by Django 4.1.3 on 2022-11-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_general'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'verbose_name_plural': 'General'},
        ),
        migrations.AlterField(
            model_name='general',
            name='chassis_height',
            field=models.CharField(default='N, Нормална', max_length=24),
        ),
    ]
