# Generated by Django 4.1.2 on 2022-10-26 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0002_alter_vehicle_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='assembly_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
