# Generated by Django 4.1.2 on 2022-10-26 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0003_vehicle_assembly_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='entry_into_service',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
