# Generated by Django 4.1.2 on 2022-10-27 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0006_remove_vehicle_licence_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicencePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.CharField(max_length=8, unique=True)),
                ('is_valid', models.BooleanField()),
                ('validity', models.DateField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maint.vehicle')),
            ],
        ),
    ]
