# Generated by Django 4.1.2 on 2022-10-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0007_licenceplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=17, unique=True, verbose_name='Vehicle identification number (VIN)'),
        ),
    ]
