# Generated by Django 4.1.2 on 2022-10-27 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0008_alter_vehicle_vin'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_stroke_volume', models.CharField(default='13', max_length=2)),
                ('power_code', models.CharField(default='410hp', max_length=5)),
                ('engine_type_vehicle', models.CharField(default='DC13 115/410hp', max_length=14)),
                ('engine_type_symbol', models.CharField(default='DC13 115 L01', max_length=12)),
                ('engine_serial_no', models.CharField(max_length=7)),
                ('cylinder_block_generation', models.CharField(default='2', max_length=1)),
                ('engine_speed_limit_with_low_oil_presure', models.BooleanField(default='Without')),
                ('egr_system', models.CharField(default='Without', max_length=14)),
                ('egr_cooling', models.CharField(default='Not valid', max_length=14)),
                ('emmission_level', models.CharField(default='Euro 6', max_length=14)),
                ('engine_management_system', models.CharField(default='S8', max_length=2)),
                ('nox_control', models.CharField(default='With', max_length=14)),
                ('torque_reduction_nox_control', models.CharField(default='With', max_length=14)),
                ('power_take_of_ED', models.CharField(default='Prepared', max_length=14)),
                ('power_take_of_ED_electical_preparation', models.CharField(default='Without', max_length=14)),
                ('power_take_of_ED_control', models.CharField(default='Without', max_length=14)),
                ('turbocharger_duty_class', models.CharField(default='Special', max_length=14)),
                ('precleaner_air_intake', models.CharField(default='Without', max_length=14)),
                ('air_intake', models.CharField(default='Front, normal', max_length=14)),
                ('air_cleaner_engine_fire_resistant', models.CharField(default='Without', max_length=14)),
                ('air_cleaner_safety_filter', models.CharField(default='Without', max_length=14)),
                ('air_cleaner_engine_paper_area', models.CharField(default='13m²', max_length=14)),
                ('air_intake_throttle_engine', models.CharField(default='With', max_length=14)),
                ('air_intake_throttle_control', models.CharField(default='Electronic', max_length=14)),
                ('air_filter_clogged_indicator', models.CharField(default='Electronic', max_length=14)),
                ('noise_dampering', models.CharField(default='80 dBA acc to 70/157/EEC', max_length=64)),
                ('crankcase_ventilation_type', models.CharField(default='Open', max_length=14)),
                ('crankcase_ventilation_antitreeze', models.CharField(default='Without', max_length=14)),
                ('oil_level_sensor_engine', models.CharField(default='Without', max_length=14)),
                ('oil_level_sensor_monitoring', models.CharField(default='Without', max_length=14)),
                ('oil_sump_material', models.CharField(default='Plastic', max_length=14)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maint.vehicle')),
            ],
        ),
    ]
