# Generated by Django 4.1.2 on 2022-10-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0009_engineinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineinfo',
            name='engine_speed_limit_with_low_oil_presure',
            field=models.CharField(default='Without', max_length=14),
        ),
    ]
