# Generated by Django 4.1.2 on 2022-10-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0010_alter_engineinfo_engine_speed_limit_with_low_oil_presure'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineinfo',
            name='noise_encapsulation_engine',
            field=models.CharField(default='With absorbents', max_length=18),
        ),
    ]
