# Generated by Django 4.1.2 on 2022-10-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0011_engineinfo_noise_encapsulation_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineinfo',
            name='power_take_of_ED_electical_preparation',
            field=models.CharField(default='Without', max_length=18),
        ),
    ]
