# Generated by Django 4.0.2 on 2022-10-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0012_alter_engineinfo_power_take_of_ed_electical_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineinfo',
            name='power_take_of_ED',
            field=models.CharField(default='Prepared', max_length=24),
        ),
    ]
