# Generated by Django 4.0.2 on 2022-10-28 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0013_alter_engineinfo_power_take_of_ed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_limiter', models.CharField(default='Има', max_length=12)),
                ('speed_limitаtion', models.CharField(default='85km/h', max_length=12)),
                ('speed_limit_second', models.CharField(default='Нема', max_length=12)),
                ('speed_limit_third', models.CharField(default='Нема', max_length=12)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maint.vehicle')),
            ],
        ),
    ]
