# Generated by Django 4.0.2 on 2022-10-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0014_enginecontrol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineinfo',
            old_name='engine',
            new_name='vehicle',
        ),
    ]
