# Generated by Django 4.0.2 on 2022-10-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0015_rename_engine_engineinfo_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineinfo',
            name='air_intake',
            field=models.CharField(default='Front, normal', max_length=18),
        ),
        migrations.AlterField(
            model_name='engineinfo',
            name='oil_sump_material',
            field=models.CharField(default='Пластика', max_length=14),
        ),
        migrations.AlterField(
            model_name='engineinfo',
            name='turbocharger_duty_class',
            field=models.CharField(default='Специјална', max_length=14),
        ),
    ]
