# Generated by Django 4.0.2 on 2022-10-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0016_alter_engineinfo_air_intake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineinfo',
            name='power_take_of_ED_electical_preparation',
            field=models.CharField(default='Without', max_length=24),
        ),
    ]
