# Generated by Django 4.0.2 on 2022-10-28 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0017_alter_engineinfo_power_take_of_ed_electical_preparation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_axle_type', models.CharField(default='ADA740', max_length=12)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maint.vehicle')),
            ],
        ),
    ]
