# Generated by Django 4.0.2 on 2022-10-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0018_frontaxle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontaxle',
            name='front_axle_type',
            field=models.CharField(default='AM740', max_length=12),
        ),
    ]
