# Generated by Django 4.1.2 on 2022-10-31 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0019_alter_frontaxle_front_axle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementaryEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fifth_wheel', models.CharField(default='JOST JSK37C-Z 150', max_length=24)),
                ('fifth_wheel_position', models.CharField(default='660', max_length=12)),
                ('fifth_wheel_category', models.CharField(default='Fixed, plate-mounted', max_length=24)),
                ('fifth_wheel_mounting_plate', models.CharField(default='40mm Dmax:152kN', max_length=24)),
                ('catwalk', models.CharField(default='Single', max_length=24)),
                ('bracket_front_mounted_equipment', models.CharField(default='Without', max_length=24)),
                ('acl_aut_chassis_lubrication', models.CharField(default='Without', max_length=24)),
                ('dimension_ja_bep_lo2o', models.CharField(default='775', max_length=24)),
                ('trailer_electric_connector', models.CharField(default='1x15 pole', max_length=24)),
                ('trailer_connector_type', models.CharField(default='1x15 pole', max_length=24)),
                ('side_skirts', models.CharField(default='Without', max_length=24)),
                ('resque_equip_except_fire_ex', models.CharField(default='With', max_length=24)),
                ('hose_tyre_inflation', models.CharField(default='20', max_length=24)),
                ('spare_wheel_carrier', models.CharField(default='20', max_length=24)),
                ('fire_extinguisher', models.CharField(default='1 x 2kg', max_length=24)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maint.vehicle')),
            ],
        ),
    ]
