# Generated by Django 4.1.2 on 2022-10-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0021_alter_complementaryequipment_acl_aut_chassis_lubrication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementaryequipment',
            name='side_skirts',
            field=models.CharField(default='Without', max_length=36),
        ),
    ]
