# Generated by Django 4.1.2 on 2022-10-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0022_alter_complementaryequipment_side_skirts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementaryequipment',
            name='catwalk',
            field=models.CharField(default='Единечна', max_length=24),
        ),
    ]
