# Generated by Django 4.1.2 on 2022-10-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0023_alter_complementaryequipment_catwalk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementaryequipment',
            name='bracket_front_mounted_equipment',
            field=models.CharField(default='Нема', max_length=24),
        ),
    ]
