# Generated by Django 4.1.2 on 2022-10-29 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DIN933',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_length', models.IntegerField()),
                ('material', models.DecimalField(decimal_places=1, max_digits=2)),
                ('finish', models.CharField(default='Plain Steel', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='M', max_length=6)),
                ('din933', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fasteners.din933')),
            ],
        ),
    ]
