# Generated by Django 4.1.2 on 2022-10-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasteners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='din933',
            options={'verbose_name_plural': 'DIN 933'},
        ),
        migrations.AddField(
            model_name='size',
            name='code',
            field=models.CharField(default='801 951', max_length=9),
        ),
    ]
