# Generated by Django 4.1.2 on 2022-10-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasteners', '0002_alter_din933_options_size_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='din933',
            options={'ordering': ['thread_length'], 'verbose_name': 'Full Thread DIN 933', 'verbose_name_plural': 'DIN 933 Full Thread'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'DIN 933 Size', 'verbose_name_plural': 'DIN 933 Size'},
        ),
        migrations.AlterField(
            model_name='din933',
            name='material',
            field=models.DecimalField(decimal_places=1, default='8.8', max_digits=2),
        ),
        migrations.AlterField(
            model_name='size',
            name='code',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
