# Generated by Django 4.1.2 on 2022-10-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasteners', '0003_alter_din933_options_alter_size_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
