# Generated by Django 4.1.2 on 2022-10-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasteners', '0005_din931_size931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='Size933',
        ),
    ]
