# Generated by Django 4.1.2 on 2022-10-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasteners', '0006_rename_size_size933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('standard', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterModelOptions(
            name='din931',
            options={'ordering': ['thread_length'], 'verbose_name': 'Partly Thread DIN 931', 'verbose_name_plural': 'DIN 931 Partly Thread'},
        ),
    ]
