# Generated by Django 4.1.2 on 2022-10-30 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fasteners', '0008_alter_screws_options_alter_screws_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIN6921',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_length', models.IntegerField()),
                ('material', models.DecimalField(decimal_places=1, default='8.8', max_digits=2)),
                ('finish', models.CharField(default='Plain Steel', max_length=24)),
            ],
            options={
                'verbose_name': 'Hexagon Head Screws, With Flange DIN 6921',
                'verbose_name_plural': 'DIN 6921 Partly Thread',
                'ordering': ['thread_length'],
            },
        ),
        migrations.CreateModel(
            name='Size6921',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='M', max_length=6)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('din6921', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fasteners.din6921')),
            ],
            options={
                'verbose_name': 'DIN 6921 Size',
                'verbose_name_plural': 'DIN 6921 Size',
            },
        ),
    ]
