# Generated by Django 4.1.2 on 2022-10-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fasteners', '0009_din6921_size6921'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIN912',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_length', models.IntegerField()),
                ('material', models.DecimalField(decimal_places=1, default='8.8', max_digits=2)),
                ('finish', models.CharField(default='Plain Steel', max_length=24)),
            ],
            options={
                'verbose_name': 'Hexagon Socked Head Cap Screws DIN 912',
                'verbose_name_plural': 'DIN  912',
                'ordering': ['thread_length'],
            },
        ),
        migrations.CreateModel(
            name='Size912',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='M', max_length=6)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('din912', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fasteners.din912')),
            ],
            options={
                'verbose_name': 'DIN 912 Size',
                'verbose_name_plural': 'DIN 912 Size',
            },
        ),
    ]
