# Generated by Django 4.1.2 on 2022-10-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasteners', '0010_din912_size912'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIN7981',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screw_length', models.IntegerField()),
                ('st35', models.CharField(blank=True, max_length=7, unique=True)),
                ('st42', models.CharField(blank=True, max_length=7, unique=True)),
                ('st48', models.CharField(blank=True, max_length=7, unique=True)),
                ('st55', models.CharField(blank=True, max_length=7, unique=True)),
                ('st63', models.CharField(blank=True, max_length=7, unique=True)),
            ],
        ),
    ]
