# Generated by Django 4.1.2 on 2022-10-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasteners', '0011_din7981'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='din7981',
            options={'verbose_name': 'DIN 7981C', 'verbose_name_plural': 'DIN 7981C'},
        ),
        migrations.AlterField(
            model_name='din7981',
            name='screw_length',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
