# Generated by Django 4.1.2 on 2022-10-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasteners', '0012_alter_din7981_options_alter_din7981_screw_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='din7981',
            name='st35',
            field=models.CharField(default='-', max_length=7),
        ),
        migrations.AlterField(
            model_name='din7981',
            name='st42',
            field=models.CharField(default='-', max_length=7),
        ),
        migrations.AlterField(
            model_name='din7981',
            name='st48',
            field=models.CharField(default='-', max_length=7),
        ),
        migrations.AlterField(
            model_name='din7981',
            name='st55',
            field=models.CharField(default='-', max_length=7),
        ),
        migrations.AlterField(
            model_name='din7981',
            name='st63',
            field=models.CharField(default='-', max_length=7),
        ),
    ]
