# Generated by Django 4.1.2 on 2022-10-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasteners', '0013_alter_din7981_st35_alter_din7981_st42_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='din7981',
            options={'ordering': ['-screw_length'], 'verbose_name': 'DIN 7981C', 'verbose_name_plural': 'DIN 7981C'},
        ),
    ]
