# Generated by Django 4.1.2 on 2022-10-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasteners', '0015_alter_din7981_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISO14583',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screw_length', models.CharField(max_length=7, unique=True)),
                ('st2_9', models.CharField(default='-', max_length=7)),
                ('st3_5', models.CharField(default='-', max_length=7)),
                ('st4_2', models.CharField(default='-', max_length=7)),
                ('st4_8', models.CharField(default='-', max_length=7)),
                ('st5_5', models.CharField(default='-', max_length=7)),
                ('st6_3', models.CharField(default='-', max_length=7)),
            ],
            options={
                'verbose_name': 'ISO 14583',
                'verbose_name_plural': 'ISO 14583',
                'ordering': ['screw_length'],
            },
        ),
    ]
