# Generated by Django 4.1.2 on 2022-10-31 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasteners', '0018_din7500d'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='din7500d',
            options={'ordering': ['screw_length'], 'verbose_name': ' DIN7500D', 'verbose_name_plural': ' DIN7500D'},
        ),
        migrations.AlterModelOptions(
            name='iso14583',
            options={'ordering': ['screw_length'], 'verbose_name': 'ISO 14583', 'verbose_name_plural': 'ISO 14583'},
        ),
    ]
